### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by domioedition** [ValValeria/phplab-tasks-1#1]
Почитай про PSR-12 https://www.php-fig.org/psr/psr-12/#51-if-elseif-else
Там расписано, как рекомендуется использовать скобки и условные операторы. Можно и нужно прочитать весь раздел.

1) getMinuteQuarter() - это простая задача, которая должна решаться простыми условиями if /elseif / else. Если подставить знаечение 0, то результат должен быть "fourth".

2) isLeapYear() - каким еще способом можно решить эту задачу?(уже есть готовая функция date в php) 

3) isSumEqual() - Тесты проходит, задача решена, но возможно ли найти более простое решение?

4) snakeCaseToCamelCase - необходимо чтоб функция из строки "this_is_home_task" вернула "thisIsHomeTask".
Знание генераторов это круто! Но как такой код будет работать на версии 5.4?
Да и вообще целесообразно ли использовать генераторы для решения этой задачи?

5) mirrorMultibyteString - тесты проходит, но возможно ли решить эту задачу в рамках одной функции?

6) getBrandName - тысты проходит, но как решить без регулярных выражений, а используя строковые функции?

7) repeatArrayValues - отлично!

8) getUniqueValue - задача решена, но сшком много манипуляций для решения.

9) groupByTag - не проходит тесты ([0] => potato, [1] => orange ,а должно быть наоборот. Первый елемент orange, второй potato). Использовано очень много разных функций. Как еще можно решить эту задачу используя только foreach, sort ?

**Comment by ValValeria** [comment]
Я изменила getMinuteQuarter, groupByTag, mirrorMultibyteString, getMinuteQuarter, isLeapYear

**Comment by domioedition** [comment]
ok, чекну на выходных
